name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Code format
    runs-on: ubuntu-latest
    steps:
      - name: Format
        run: cargo fmt --verbose --check

  build:
    name: Build for ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: cargo build --verbose

      - name: Lint
        run: cargo clippy --verbose

      - name: Test
        run: cargo test --verbose

  build-diesel-feature:
    name: Build with diesel feature
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: cargo build --verbose --features diesel

      - name: Lint
        run: cargo clippy --verbose --features diesel

      - name: Test
        run: cargo test --verbose --features diesel
