name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3

      - name: Lint
        run: cargo clippy

  build:
    name: Build & test on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose

  build-diesel-feature:
    name: Build & test with diesel feature
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3

      - name: Build
        run: cargo build --verbose --features diesel

      - name: Test
        run: cargo test --verbose --features diesel
